variables:
  CI_REGISTRY_FULL: "platform52.gitlab.yandexcloud.net:5050/avtomat/avtomat-backend-api"
  DOCKER_NETWORK: "avtomat"
  PORT: "-p 127.0.0.1:3002:80"

stages:
  - build
  - deploy

build:backend-api:dev:
  stage: build
  script:
    - echo "Compiling the code..."
    - cat ./deploy/.env.development > .env
    - echo $ENV_DEV_B64_SECRETS | base64 -d >> .env
    - echo $NPMRC_DEV_B64 | base64 -d > .npmrc
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_FULL
    - docker pull $CI_REGISTRY_FULL:$CI_COMMIT_SHORT_SHA || true
    - docker build --tag $CI_REGISTRY_FULL:$CI_COMMIT_SHORT_SHA -f Dockerfile .
    - docker push $CI_REGISTRY_FULL:$CI_COMMIT_SHORT_SHA
    - docker system prune -a -f
    - echo "Compile complete."
  rules:
    - if: ($CI_COMMIT_REF_NAME == "dev" || $CI_MERGE_REQUEST_ID)
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - script_failure
  tags:
    - avtomat-dev

deploy:backend-api:dev:
  stage: deploy
  variables:
    APP_SERVICE: "avtomat-backend-api-dev"
    CMD_MIGRATION: "npm run migration:run:prod"
    CMD: "node main.js"
  script:
    - echo "Deploying application..."
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY_FULL
    - docker pull $CI_REGISTRY_FULL:$CI_COMMIT_SHORT_SHA || true
    - docker stop $APP_SERVICE || true
    - docker rm $APP_SERVICE || true
    - docker network create $DOCKER_NETWORK || true
    - docker run --name $APP_SERVICE --network $DOCKER_NETWORK $PORT $CI_REGISTRY_FULL:$CI_COMMIT_SHORT_SHA $CMD_MIGRATION
    - docker stop $APP_SERVICE || true
    - docker rm $APP_SERVICE || true
    - docker run -d --name $APP_SERVICE --network $DOCKER_NETWORK --restart unless-stopped $PORT $CI_REGISTRY_FULL:$CI_COMMIT_SHORT_SHA $CMD
    - docker system prune -a -f
    - echo "Application successfully deployed."
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev"
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure
      - script_failure
  tags:
    - avtomat-dev-3